# Top level design name
HARDWARE := lbl208
PROJECT_PART := xczu47dr-ffvg1517-1-e
PROJECT_BOARD := none
FPGA_PLATFORM := zu47
TARGET := dsbpm_vcxo_160_lbl208
FPGA_APPLICATION := dsbpm_vcxo_160

include ../common_dsbpm/Makefile
