##################################################################
# CREATE IP evrGTY
##################################################################

set evrGTY [create_ip -name gtwizard_ultrascale -vendor xilinx.com -library ip -version 1.7 -module_name evrGTY]

set_property -dict { 
  CONFIG.CHANNEL_ENABLE {X0Y8}
  CONFIG.TX_MASTER_CHANNEL {X0Y8}
  CONFIG.RX_MASTER_CHANNEL {X0Y8}
  CONFIG.RX_PPM_OFFSET {200}
  CONFIG.INS_LOSS_NYQ {14}
  CONFIG.TX_LINE_RATE {2.5}
  CONFIG.TX_PLL_TYPE {CPLL}
  CONFIG.TX_REFCLK_FREQUENCY {156.25}
  CONFIG.TX_DATA_ENCODING {8B10B}
  CONFIG.TX_USER_DATA_WIDTH {16}
  CONFIG.TX_INT_DATA_WIDTH {20}
  CONFIG.TX_BUFFER_MODE {1}
  CONFIG.TX_OUTCLK_SOURCE {TXPROGDIVCLK}
  CONFIG.RX_LINE_RATE {2.5}
  CONFIG.RX_PLL_TYPE {CPLL}
  CONFIG.RX_REFCLK_FREQUENCY {156.25}
  CONFIG.RX_DATA_DECODING {8B10B}
  CONFIG.RX_USER_DATA_WIDTH {16}
  CONFIG.RX_INT_DATA_WIDTH {20}
  CONFIG.RX_BUFFER_MODE {0}
  CONFIG.RX_EQ_MODE {AUTO}
  CONFIG.RX_JTOL_FC {1.4997001}
  CONFIG.RX_COMMA_PRESET {K28.5}
  CONFIG.RX_COMMA_P_ENABLE {true}
  CONFIG.RX_COMMA_M_ENABLE {true}
  CONFIG.RX_COMMA_MASK {1111111111}
  CONFIG.RX_COMMA_ALIGN_WORD {2}
  CONFIG.RX_COMMA_SHOW_REALIGN_ENABLE {true}
  CONFIG.RX_SLIDE_MODE {PCS}
  CONFIG.RX_CB_NUM_SEQ {0}
  CONFIG.RX_CB_MAX_SKEW {1}
  CONFIG.RX_CB_VAL_0_0 {00000000}
  CONFIG.RX_CB_K_0_0 {false}
  CONFIG.RX_CC_NUM_SEQ {0}
  CONFIG.RX_CC_LEN_SEQ {1}
  CONFIG.RX_CC_VAL {00000000000000000000000000000000000000000000000000000000000000000000000000000000}
  CONFIG.RX_CC_VAL_0_0 {00000000}
  CONFIG.RX_CC_K_0_0 {false}
  CONFIG.RX_CC_VAL_0_1 {00000000}
  CONFIG.RX_CC_K_0_1 {false}
  CONFIG.ENABLE_OPTIONAL_PORTS {cplllockdetclk_in cplllocken_in cpllreset_in drpaddr_in drpclk_in drpdi_in drpen_in drpwe_in eyescanreset_in loopback_in cplllock_out drpdo_out drprdy_out}
  CONFIG.RX_REFCLK_SOURCE {X0Y8 clk1+2}
  CONFIG.TX_REFCLK_SOURCE {X0Y8 clk1+2}
  CONFIG.LOCATE_TX_BUFFER_BYPASS_CONTROLLER {CORE}
  CONFIG.LOCATE_TX_USER_CLOCKING {CORE}
  CONFIG.LOCATE_RX_USER_CLOCKING {CORE}
  CONFIG.PRESET {GTY-Aurora_8B10B}
  CONFIG.INTERNAL_PRESET {Aurora_8B10B}
  CONFIG.TXPROGDIV_FREQ_SOURCE {CPLL}
  CONFIG.TXPROGDIV_FREQ_VAL {125}
  CONFIG.FREERUN_FREQUENCY {100}
} [get_ips evrGTY]

set_property -dict { 
  GENERATE_SYNTH_CHECKPOINT {1}
} $evrGTY

##################################################################
