stages:
  - prepare
  - gateware
  - software

default:
  tags:
    - xilinx-bookworm

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2022.1/Vivado/2022.1
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2022.1/Vitis/2022.1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gw_dsbpm_vcxo_160_zcu208:
  before_script:
    - cd gateware/syn/dsbpm_vcxo_160_zcu208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make dsbpm_vcxo_160_zcu208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - gateware/syn/dsbpm_vcxo_160_zcu208/dsbpm_vcxo_160_zcu208_top.bit
      - gateware/syn/dsbpm_vcxo_160_zcu208/_xilinx/dsbpm_vcxo_160_zcu208_top/*.runs/impl_1/*.rpt
      - gateware/syn/dsbpm_vcxo_160_zcu208/system.xsa

gw_dsbpm_vcxo_117_zcu208:
  before_script:
    - cd gateware/syn/dsbpm_vcxo_117_zcu208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make dsbpm_vcxo_117_zcu208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - gateware/syn/dsbpm_vcxo_117_zcu208/dsbpm_vcxo_117_zcu208_top.bit
      - gateware/syn/dsbpm_vcxo_117_zcu208/_xilinx/dsbpm_vcxo_117_zcu208_top/*.runs/impl_1/*.rpt
      - gateware/syn/dsbpm_vcxo_117_zcu208/system.xsa

gw_dsbpm_vcxo_160_lbl208:
  before_script:
    - cd gateware/syn/dsbpm_vcxo_160_lbl208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make dsbpm_vcxo_160_lbl208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - gateware/syn/dsbpm_vcxo_160_lbl208/dsbpm_vcxo_160_lbl208_top.bit
      - gateware/syn/dsbpm_vcxo_160_lbl208/_xilinx/dsbpm_vcxo_160_lbl208_top/*.runs/impl_1/*.rpt
      - gateware/syn/dsbpm_vcxo_160_lbl208/system.xsa

gw_dsbpm_vcxo_117_lbl208:
  before_script:
    - cd gateware/syn/dsbpm_vcxo_117_lbl208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make dsbpm_vcxo_117_lbl208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - gateware/syn/dsbpm_vcxo_117_lbl208/dsbpm_vcxo_117_lbl208_top.bit
      - gateware/syn/dsbpm_vcxo_117_lbl208/_xilinx/dsbpm_vcxo_117_lbl208_top/*.runs/impl_1/*.rpt
      - gateware/syn/dsbpm_vcxo_117_lbl208/system.xsa

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
sw_dsbpm_vcxo_160_zcu208_spt81:
  before_script:
    - cd software/app/dsbpm_vcxo_160
  stage: software
  script: >
    - make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_160_zcu208 clean &&
      PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH
      make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_160_zcu208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_dsbpm_vcxo_160_zcu208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_zcu208_spt81/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_zcu208_spt81/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_zcu208_spt81.elf
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_zcu208_spt81*.bin

sw_dsbpm_vcxo_117_zcu208_spt81:
  before_script:
    - cd software/app/dsbpm_vcxo_117
  stage: software
  script: >
    - make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_117_zcu208 clean &&
      PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH
      make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_117_zcu208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_dsbpm_vcxo_117_zcu208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt81/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt81/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt81.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt81*.bin

sw_dsbpm_vcxo_160_lbl208_spt81:
  before_script:
    - cd software/app/dsbpm_vcxo_160
  stage: software
  script: >
    - make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_160_lbl208 clean &&
      PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH
      make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_160_lbl208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_dsbpm_vcxo_160_lbl208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_lbl208_spt81/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_lbl208_spt81/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_lbl208_spt81.elf
      - software/app/dsbpm_vcxo_160/dsbpm_vcxo_160_lbl208_spt81*.bin

sw_dsbpm_vcxo_117_lbl208_spt81:
  before_script:
    - cd software/app/dsbpm_vcxo_117
  stage: software
  script: >
    - make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_117_lbl208 clean &&
      PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH
      make SAMPLES_PER_TURN=81 TARGET=dsbpm_vcxo_117_lbl208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_dsbpm_vcxo_117_lbl208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt81/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt81/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt81.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt81*.bin

sw_dsbpm_vcxo_117_zcu208_spt77:
  before_script:
    - cd software/app/dsbpm_vcxo_117
  stage: software
  script: >
    - make SAMPLES_PER_TURN=77 TARGET=dsbpm_vcxo_117_zcu208 clean &&
      PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH
      make SAMPLES_PER_TURN=77 TARGET=dsbpm_vcxo_117_zcu208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_dsbpm_vcxo_117_zcu208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt77/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt77/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt77.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_zcu208_spt77*.bin

sw_dsbpm_vcxo_117_lbl208_spt77:
  before_script:
    - cd software/app/dsbpm_vcxo_117
  stage: software
  script: >
    - make SAMPLES_PER_TURN=77 TARGET=dsbpm_vcxo_117_lbl208 clean &&
      PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH
      make SAMPLES_PER_TURN=77 TARGET=dsbpm_vcxo_117_lbl208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_dsbpm_vcxo_117_lbl208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt77/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt77/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt77.elf
      - software/app/dsbpm_vcxo_117/dsbpm_vcxo_117_lbl208_spt77*.bin
