stages:
  - prepare
  - gateware
  - software

default:
  tags:
    - xilinx-bookworm

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2022.1/Vivado/2022.1
  XILINX_VITIS: /non-free/Xilinx/Vivado_and_Vitis/2022.1/Vitis/2022.1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

# Gateware jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description, as to simplify job descriptions
gw_dsbpm_zcu208:
  before_script:
    - cd gateware/syn/dsbpm_zcu208 && ls /non-free
  stage: gateware
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH make dsbpm_zcu208_top.bit
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - gateware/syn/dsbpm_zcu208/dsbpm_zcu208_top.bit
      - gateware/syn/dsbpm_zcu208/_xilinx/dsbpm_zcu208_top/*.runs/impl_1/*.rpt
      - gateware/syn/dsbpm_zcu208/system.xsa

# Software jobs
# Gitlab doesn't seem to suport the usage of variables in
# a "dependencies" or "needs" statement. So, unroll the job
# description...
sw_dsbpm_zcu208:
  before_script:
    - cd software/app/dsbpm
  stage: software
  script:
    - make TARGET=dsbpm_zcu208 clean && PATH=$XILINX_VITIS/bin:$XILINX_VITIS/gnu/aarch64/lin/aarch64-none/bin:$PATH make TARGET=dsbpm_zcu208
  # Get artifacts from this job, needed to compile the sofware
  needs:
    - job: gw_dsbpm_zcu208
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - software/app/dsbpm/dsbpm_zcu208/platform/zynqmp_fsbl/fsbl_a53.elf
      - software/app/dsbpm/dsbpm_zcu208/platform/export/platform/sw/platform/boot/pmufw.elf
      - software/app/dsbpm/dsbpm_zcu208.elf
      - software/app/dsbpm/dsbpm_zcu208*.bin
