# Top level design name
HARDWARE := zcu208
PROJECT_PART := xczu48dr-fsvg1517-2-e
PROJECT_BOARD := xilinx.com:zcu208:part0:2.0
FPGA_PLATFORM := zu48
TARGET := dsbpm_vcxo_160_zcu208
FPGA_APPLICATION := dsbpm_vcxo_160

include ../common_dsbpm/Makefile
