# Top level design name
HARDWARE := lbl208
PROJECT_PART := xczu47dr-ffvg1517-1-e
PROJECT_BOARD := none
FPGA_PLATFORM := zu47
TARGET := dsbpm_lbl208
FPGA_APPLICATION := dsbpm

BD_SYSTEM_NAME ?= system

include ../common_dsbpm/Makefile
